version: '3'

services:

  database:
    image: mysql:5.6
    restart: always
    volumes:
      - ./raw_fr.sql:/docker-entrypoint-initdb.d/raw_fr.sql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: raw_fr
      MYSQL_TCP_PORT: 3307
    expose:
      - 3307
    network_mode: "host"

  default-fr:
    restart: always
    build: .
    image: default-fr
    command: ["gunicorn", "-b", "127.0.0.1:8000", "--worker-class", "gthread", "-w", "1", "--threads", "1", "app:app"]
    depends_on:
      - database
    # links:
    #   - database
    expose: 
      - 8000
      - 443
    network_mode: "host"

  server:
    restart: always
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - default-fr
    # links:
    #   - default-cr:default-cr
    ports:
      - "80:80"
    network_mode: "host"